In [26]:
import pandas as pd

In [27]:
AAPL_df = pd.read_csv("AAPL_historical_data.csv")

AAPL_df.head(10)

,Date,Adj Close,Close,High,Low,Open,Volume
0,2021-10-01,139.136673,142.649994,142.919998,139.110001,141.899994,94639600
1,2021-10-04,135.713120,139.139999,142.210007,138.270004,141.759995,98322000
2,2021-10-05,137.634628,141.110001,142.240005,139.360001,139.490005,80861100
3,2021-10-06,138.502716,142.000000,142.149994,138.369995,139.470001,83221100
4,2021-10-07,139.760910,143.289993,144.220001,142.720001,143.059998,61732700
5,2021-10-08,139.380539,142.899994,144.179993,142.559998,144.029999,58773200
6,2021-10-11,139.292725,142.809998,144.809998,141.809998,142.270004,64452200
7,2021-10-12,138.024780,141.509995,143.250000,141.039993,143.229996,73035900
8,2021-10-13,137.439545,140.910004,141.399994,139.199997,141.240005,78762700
9,2021-10-14,140.219345,143.759995,143.880005,141.509995,142.110001,69907100

In [28]:
AAPL_df.describe()

,Adj Close,Close,High,Low,Open,Volume
count,1254.000000,1254.000000,1254.000000,1254.000000,1254.000000,1.254000e+03
mean,202.613590,204.591228,206.634761,202.336962,204.354880,6.357783e+07
std,51.261960,50.366183,50.775127,49.893761,50.294542,2.855109e+07
min,122.827606,125.019997,127.769997,124.169998,126.010002,1.791060e+07
25%,162.922287,166.140003,167.872498,164.590000,166.092499,4.489712e+07
50%,189.051575,191.264999,192.620003,189.700005,190.959999,5.517040e+07
75%,234.510593,236.359997,238.145000,233.420002,235.509995,7.514605e+07
max,341.070007,341.070007,345.339996,338.750000,341.079987,3.186799e+08

In [29]:
AAPL_df.shape

(1254, 7)

followed the 5(a) loading method

In [30]:
AAPL_df = pd.read_csv("AAPL_historical_data.csv", parse_dates = ['Date'], index_col = 'Date')

In [31]:
AAPL_df.head(10)

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2021-10-01,139.136673,142.649994,142.919998,139.110001,141.899994,94639600
2021-10-04,135.713120,139.139999,142.210007,138.270004,141.759995,98322000
2021-10-05,137.634628,141.110001,142.240005,139.360001,139.490005,80861100
2021-10-06,138.502716,142.000000,142.149994,138.369995,139.470001,83221100
2021-10-07,139.760910,143.289993,144.220001,142.720001,143.059998,61732700
2021-10-08,139.380539,142.899994,144.179993,142.559998,144.029999,58773200
2021-10-11,139.292725,142.809998,144.809998,141.809998,142.270004,64452200
2021-10-12,138.024780,141.509995,143.250000,141.039993,143.229996,73035900
2021-10-13,137.439545,140.910004,141.399994,139.199997,141.240005,78762700
2021-10-14,140.219345,143.759995,143.880005,141.509995,142.110001,69907100

In [32]:
# Drop null values from the dataframe
AAPL_df = AAPL_df.dropna()

# Display the sumof null values
AAPL_df.isnull().sum()

Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [33]:
AAPL_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1254 entries, 2021-10-01 to 2026-09-30
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Adj Close  1254 non-null   float64
 1   Close      1254 non-null   float64
 2   High       1254 non-null   float64
 3   Low        1254 non-null   float64
 4   Open       1254 non-null   float64
 5   Volume     1254 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 68.6 KB